version: '3'
services:
  srsgnb_zmq:
    image: docker_srsran
    container_name: srsgnb_zmq
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./srsran:/mnt/srsran
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=gnb_zmq
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_GNB_IP}
  
  metrics-server:
    container_name: metrics_server
    image: softwareradiosystems/metrics-server:e5d5b44b92__2024-12-03
    environment:
      - PORT=${METRICS_SERVER_PORT}
      - BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - TESTBED=default
      - URL=http://${DOCKER_INFLUXDB_INIT_HOST}:${DOCKER_INFLUXDB_INIT_PORT}
      - ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - 55555:${METRICS_SERVER_PORT}/udp
    networks:
      default:
        ipv4_address: ${METRICS_SERVER_IP}

  influxdb:
    container_name: influxdb
    image: influxdb:${DOCKER_INFLUXDB_VERSION}
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    restart: on-failure:10
    # Uncomment port section to access InfluxDB from outside the docker network
    ports:
      - 8086:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      default:
        ipv4_address: ${DOCKER_INFLUXDB_IP}

  srsran_gnb_grafana:
    container_name: srsran_gnb_grafana
    image: softwareradiosystems/grafana:e5d5b44b92__2024-12-03
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - metrics-server
    ports:
      - 3300:${GRAFANA_PORT}
    networks:
      default:
        ipv4_address: ${SRSGNB_GRAFANA_IP}

volumes:
  gnb-storage:
  grafana-storage:
  influxdb-storage:

networks:
  default:
    external:
      name: docker_open5gs_default
